name: SudoJG
version: 1.0.1
api: [3.11.4]
author: JGYTVevo
main: JGYTVevo\SudoJG\Main
commands:
  sjg:
    description: Force a player to chat or run a command
    usage: /sjg <player> <message or /command..>
permissions:
  sjg.command:
    default: op
    description: Allows player to use /sudo
