name: SudoJG
version: 1.0.0
api: [3.0.0]
author: JGYTVevo
main: JGYTVevo\SudoJG\Main
commands:
  sudo:
    description: Force a player to chat or run a command
    usage: /sudo <player> <message or /command..>
permissions:
  sudo.command:
    default: op
    description: Allows player to use /sudo
